INSERT INTO VEHICLE VALUES (vehicleNo,modeltype,color,pricebranch,available,fueltype,manual,sizetype);

INSERT INTO VEHICLE VALUES (1,Mercedes-Benz Tourino,white,30,hougang,1);
INSERT INTO BUS (bus,diesel,manual,30,1);
INSERT INTO VEHICLE VALUES (2,Mercedes-Benz Travego,yellow,40,woodlands,1);
INSERT INTO BUS (bus,diesel,manual,20,2);
INSERT INTO VEHICLE VALUES (3,Mercedes-Benz Tourismo,grey,45,woodlands,1);
INSERT INTO BUS (bus,diesel,manual,30,3);
INSERT INTO VEHICLE VALUES (4,Mercedes-Benz Citaro,blue,50,tampines,1);
INSERT INTO BUS (bus,diesel,manual,40,4);
INSERT INTO VEHICLE VALUES (5,Scania Touring,white,30,tampines,1);
INSERT INTO BUS (bus,diesel,manual,20,5);
INSERT INTO VEHICLE VALUES (6,Volvo 9500,white,40,woodlands,1);
INSERT INTO BUS (bus,diesel,manual,20,6);
INSERT INTO VEHICLE VALUES (7,Volvo 9900,gold,45,hougang,1);
INSERT INTO BUS (bus,diesel,manual,30,7);
INSERT INTO VEHICLE VALUES (8,Volvo 9700,blue,50,tampines,1);
INSERT INTO BUS (bus,diesel,manual,40,8);
INSERT INTO VEHICLE VALUES (9,King Long XMQ6130Y,orange,50,tampines,1);
INSERT INTO BUS (bus,diesel,manual,40,9);
INSERT INTO VEHICLE VALUES (10,King Long XMQ6140P,red,50,tampines,1);
INSERT INTO BUS (bus,diesel,manual,40,10);

INSERT INTO VEHICLE VALUES (11,Mercedes-Benz Vito,blue,35,hougang,1);
INSERT INTO BUS (minivan,diesel,auto,10,11);
INSERT INTO VEHICLE VALUES (12,Mercedes-Benz Vito,red,35,tampines,1);
INSERT INTO BUS (minivan,diesel,auto,10,12);
INSERT INTO VEHICLE VALUES (13,Mercedes-Benz Trave,purple,35,hougang,1);
INSERT INTO BUS (minivan,diesel,manual,10,13);
INSERT INTO VEHICLE VALUES (14,Mercedes-Benz Travel,gold,35,woodlands,1);
INSERT INTO BUS (minivan,diesel,manual,10,14);
INSERT INTO VEHICLE VALUES (15,Toyota Hiace,silver,30,tampines,1);
INSERT INTO BUS (minivan,diesel,auto,10,15);
INSERT INTO VEHICLE VALUES (16,Nissan Urvan,white,28,woodlands,1);
INSERT INTO BUS (minivan,diesel,manual,10,16);
INSERT INTO VEHICLE VALUES (17,Nissan Urvan,black,32,hougang,1);
INSERT INTO BUS (minivan,diesel,manual,10,17);
INSERT INTO VEHICLE VALUES (18,Toyota Hiace,white,30,tampines,1);
INSERT INTO BUS (minivan,diesel,auto,10,18);
INSERT INTO VEHICLE VALUES (19,Kia Combi VEHICLE,yellow,28,tampines,1);
INSERT INTO BUS (minivan,diesel,manual,10,19);
INSERT INTO VEHICLE VALUES (20,Nissan Urvan Estate,blue,28,woodlands,1);
INSERT INTO BUS (minivan,diesel,auto,10,20);